from django.conf.urls import url
from pwm_cost import views

urlpatterns = [
    url(r'^get-wafer-maps$', views.get_wafer_maps),
    url(r'^wafer$', views.WaferInfoGeneric.as_view()),
    url(r'^wafer/(?P<pk>.*?)$', views.WaferDetailGeneric.as_view()),
    url(r'^wafer-bom$', views.WaferBomGeneric.as_view()),
    url(r'^wafer-bom/(?P<pk>[0-9]+)$', views.WaferBomDetailGeneric.as_view()),
    url(r'^get-grain-maps$', views.get_grain_maps),
    url(r'^grain$', views.GrainInfoGeneric.as_view()),
    url(r'^grain/(?P<pk>.*?)$', views.GrainDetailGeneric.as_view()),
    url(r'^grain-bom$', views.GrainBomGeneric.as_view()),
    url(r'^grain-bom/(?P<pk>[0-9]+)$', views.GrainBomDetailGeneric.as_view()),
    url(r'^upload-record$', views.UploadRecordGeneric.as_view()),
    url(r'^upload-record/(?P<pk>[0-9]+)$', views.UploadRecordOperate.as_view()),
    url(r'^wafer-price$', views.WaferPriceGeneric.as_view()),
    url(r'^wafer-price/(?P<pk>[0-9]+)$', views.WaferPriceOperate.as_view()),
    url(r'^download-template$', views.get_upload_template),
    url(r'^upload-wafer-price$', views.upload_wafer_price),
    url(r'^recalculate-wafer-price$', views.recalculate_wafer_price),
    url(r'^save-wafer-price$', views.save_upload_wafer_price),
    url(r'^export-wafer-price$', views.export_wafer_price),
    url(r'^grain-yield$', views.GrainYieldGeneric.as_view()),
    url(r'^grain-yield/(?P<pk>[0-9]+)$', views.GrainYieldOperate.as_view()),
    url(r'^grain-price$', views.GrainPriceGeneric.as_view()),
    url(r'^grain-price/(?P<pk>[0-9]+)$', views.GrainPriceOperate.as_view()),
    url(r'^exist-wafer-price$', views.exist_wafer_price),
    url(r'^upload-grain-yield$', views.upload_grain_yield),
    url(r'^upload-grain-price$', views.upload_grain_price),
    url(r'^recalculate-grain-data$', views.recalculate_grain_data),
    url(r'^save-grain-data$', views.save_upload_grain_data),
    url(r'^export-grain-yield$', views.export_grain_yield),
    url(r'^export-grain-price$', views.export_grain_price),
    url(r'^init-system-users$', views.query_system_user),
    url(r'^download-source-file$', views.download_source_file),
    url(r'^get-data$', views.get_data),
]
